export type PortRisk = 'SAFE INTERNAL' | 'INTERNAL ONLY' | 'PUBLIC EXPOSURE RISK' | 'HIGH-RISK INTERNET SERVICE' | 'CRITICAL MISCONFIGURATION';

export interface PortIntelligence {
  port: number;
  name: string;
  protocol: string;
  description: string;
  commonUsage: string;
  riskClassification: PortRisk;
  warning?: string;
  hardening: string[];
}

export const PORT_ENCYCLOPEDIA: Record<number, PortIntelligence> = {
  21: {
    port: 21,
    name: 'FTP',
    protocol: 'TCP',
    description: 'File Transfer Protocol. Unencrypted file transfer mechanism.',
    commonUsage: 'Legacy file sharing and server backups.',
    riskClassification: 'HIGH-RISK INTERNET SERVICE',
    warning: 'FTP transmits passwords and data in cleartext. Extremely vulnerable to sniffing.',
    hardening: ['Use SFTP (SSH) or FTPS (TLS) instead', 'Disable anonymous login', 'Restrict via firewall'],
  },
  22: {
    port: 22,
    name: 'SSH',
    protocol: 'TCP',
    description: 'Secure Shell. Encrypted remote terminal access and file transfer.',
    commonUsage: 'Server administration, automated scripts, and secure tunneling.',
    riskClassification: 'PUBLIC EXPOSURE RISK',
    warning: 'Highly targeted by brute-force bots and credential stuffing attacks.',
    hardening: ['Disable password authentication', 'Use SSH Keys (Ed25519)', 'Change default port (optional obscurity)', 'Deploy fail2ban'],
  },
  23: {
    port: 23,
    name: 'Telnet',
    protocol: 'TCP',
    description: 'Unencrypted text communications over a network.',
    commonUsage: 'Legacy switch/router management.',
    riskClassification: 'CRITICAL MISCONFIGURATION',
    warning: 'Telnet provides zero encryption. Credentials can be read off the wire instantly.',
    hardening: ['Disable completely', 'Replace with SSH'],
  },
  25: {
    port: 25,
    name: 'SMTP',
    protocol: 'TCP',
    description: 'Simple Mail Transfer Protocol.',
    commonUsage: 'Mail server routing and relaying.',
    riskClassification: 'PUBLIC EXPOSURE RISK',
    warning: 'Unauthenticated SMTP can be abused for spam relaying.',
    hardening: ['Require STARTTLS', 'Disable open relays', 'Implement SPF/DKIM/DMARC'],
  },
  53: {
    port: 53,
    name: 'DNS',
    protocol: 'TCP/UDP',
    description: 'Domain Name System. Translates domain names to IP addresses.',
    commonUsage: 'Name resolution for local networks and internet services.',
    riskClassification: 'PUBLIC EXPOSURE RISK',
    warning: 'Open resolvers can be abused for massive DDoS amplification attacks.',
    hardening: ['Disable recursive queries for public IPs', 'Implement DNSSEC', 'Rate limit responses'],
  },
  80: {
    port: 80,
    name: 'HTTP',
    protocol: 'TCP',
    description: 'Hypertext Transfer Protocol. Unencrypted web traffic.',
    commonUsage: 'Websites, REST APIs, and legacy web panels.',
    riskClassification: 'HIGH-RISK INTERNET SERVICE',
    warning: 'Data is unencrypted. Susceptible to MitM attacks.',
    hardening: ['Enforce 301 redirects to HTTPS', 'Do not accept sensitive payloads over port 80'],
  },
  443: {
    port: 443,
    name: 'HTTPS',
    protocol: 'TCP',
    description: 'Hypertext Transfer Protocol Secure. Encrypted web traffic.',
    commonUsage: 'Standard secure port for global web services.',
    riskClassification: 'SAFE INTERNAL',
    hardening: ['Use modern TLS 1.2/1.3', 'Configure strong cipher suites', 'Implement HSTS', 'Enable WAF'],
  },
  389: {
    port: 389,
    name: 'LDAP',
    protocol: 'TCP/UDP',
    description: 'Lightweight Directory Access Protocol.',
    commonUsage: 'Active Directory queries and user authentication lookups.',
    riskClassification: 'INTERNAL ONLY',
    warning: 'Exposed LDAP can leak entire corporate directory structures and hashes.',
    hardening: ['Never expose to the internet', 'Use LDAPS (Port 636) internally'],
  },
  3306: {
    port: 3306,
    name: 'MySQL',
    protocol: 'TCP',
    description: 'Relational Database Management System.',
    commonUsage: 'Backend data storage for web applications.',
    riskClassification: 'INTERNAL ONLY',
    warning: 'Databases should never be directly accessible from the public internet.',
    hardening: ['Bind to 127.0.0.1 or VPC subnet only', 'Require strong passwords', 'Disable remote root login'],
  },
  5432: {
    port: 5432,
    name: 'PostgreSQL',
    protocol: 'TCP',
    description: 'Advanced Open Source Relational Database.',
    commonUsage: 'High-performance backend data storage.',
    riskClassification: 'INTERNAL ONLY',
    warning: 'Public exposure invites brute-force and zero-day exploitation.',
    hardening: ['Configure pg_hba.conf strictly', 'Bind to localhost/VPC', 'Enforce SSL connections'],
  },
  6379: {
    port: 6379,
    name: 'Redis',
    protocol: 'TCP',
    description: 'In-Memory Data Structure Store.',
    commonUsage: 'Caching, session management, and message brokering.',
    riskClassification: 'CRITICAL MISCONFIGURATION',
    warning: 'Redis natively lacks robust authentication. Public exposure often leads to instant ransomware/crypto-mining infection.',
    hardening: ['Require AUTH password', 'Bind to 127.0.0.1', 'Rename dangerous commands (FLUSHALL)'],
  },
  27017: {
    port: 27017,
    name: 'MongoDB',
    protocol: 'TCP',
    description: 'NoSQL Document Database.',
    commonUsage: 'Scalable data storage for modern web apps.',
    riskClassification: 'CRITICAL MISCONFIGURATION',
    warning: 'Historically shipped without auth. Public MongoDB instances are routinely wiped and held for ransom.',
    hardening: ['Enable authentication mechanisms', 'Restrict network binding', 'Use TLS/SSL'],
  },
  3389: {
    port: 3389,
    name: 'RDP',
    protocol: 'TCP',
    description: 'Remote Desktop Protocol.',
    commonUsage: 'Windows Server administration and virtual workspaces.',
    riskClassification: 'HIGH-RISK INTERNET SERVICE',
    warning: 'RDP is the #1 vector for corporate ransomware deployment (via brute force or vulnerabilities like BlueKeep).',
    hardening: ['Place behind a VPN/Gateway', 'Enforce MFA via Duo/Azure', 'Implement Account Lockout policies'],
  },
  445: {
    port: 445,
    name: 'SMB',
    protocol: 'TCP',
    description: 'Server Message Block.',
    commonUsage: 'Windows file sharing and printer sharing.',
    riskClassification: 'CRITICAL MISCONFIGURATION',
    warning: 'Exposing SMB to the internet allows lateral movement and exploitation (e.g., EternalBlue).',
    hardening: ['Block at the network edge', 'Disable SMBv1 entirely', 'Require SMB signing'],
  },
  9200: {
    port: 9200,
    name: 'Elasticsearch',
    protocol: 'TCP',
    description: 'Distributed Search and Analytics Engine.',
    commonUsage: 'Log aggregation (ELK stack) and full-text search.',
    riskClassification: 'CRITICAL MISCONFIGURATION',
    warning: 'Unauthenticated public Elasticsearch clusters leak massive amounts of PII and operational data daily.',
    hardening: ['Enable X-Pack Security', 'Use a reverse proxy (Nginx) with auth', 'Bind to local network'],
  },
  8080: {
    port: 8080,
    name: 'HTTP-ALT',
    protocol: 'TCP',
    description: 'Alternative HTTP Port.',
    commonUsage: 'Development servers, proxies (Tomcat, Jenkins), and admin panels.',
    riskClassification: 'PUBLIC EXPOSURE RISK',
    warning: 'Often hosts unauthenticated admin dashboards or vulnerable development builds.',
    hardening: ['Ensure auth is enabled', 'Use a WAF', 'Don\'t expose dev servers globally'],
  }
};
